# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build to prod'
          script:
          - pipe: atlassian/ftp-deploy:0.3.7
            variables:
              USER: 'energisol-to1'
              PASSWORD: 'eAVC.!YSEh*Yak4'
              SERVER: 'ftp.energisol-to.com.br'
              REMOTE_PATH: '/home/energisol-to1/'